import { generateComments } from './presetComments';

// 為每個預設標記生成隨機評論和平均評分
const generateMarkerData = (markerId, baseMarker) => {
  // 生成 5-15 個隨機評論
  const commentCount = Math.floor(Math.random() * 11) + 5;
  const comments = generateComments(markerId, commentCount);

  // 計算平均評分
  const averageRating = comments.length > 0
    ? comments.reduce((acc, comment) => acc + comment.rating, 0) / comments.length
    : 0;

  return {
    ...baseMarker,
    comments,
    rating: averageRating
  };
};

// 預設標記點資料
const defaultMarkers = [

  generateMarkerData("minxiong-ghost-house", {
    id: "minxiong-ghost-house",
    position: [23.554235, 120.434558],
    title: "民雄鬼屋",
    city: "嘉義縣",
    district: "民雄鄉",
    coverPhoto: "/images/default-location.jpg",
    description: "台灣知名的靈異景點，充滿神秘氣息。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("xinhai-tunnel", {
    id: "xinhai-tunnel",
    position: [25.004379, 121.541615],
    title: "辛亥隧道",
    city: "台北市",
    district: "大安區",
    coverPhoto: "/images/default-location.jpg",
    description: "曾發生多起意外，傳說有靈異現象的隧道。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("lin-kai-jun-mansion", {
    id: "lin-kai-jun-mansion",
    position: [22.627278, 120.301435],
    title: "林開郡洋樓",
    city: "高雄市",
    district: "鳳山區",
    coverPhoto: "/images/default-location.jpg",
    description: "古老的日治時期建築，據說晚上常有異象出現。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("xining-residential-complex", {
    id: "xining-residential-complex",
    position: [25.048019, 121.506609],
    title: "西寧國宅",
    city: "台北市",
    district: "萬華區",
    coverPhoto: "/images/default-location.jpg",
    description: "老舊國宅，居民口中流傳著靈異故事。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("keelung-haunted-hospital", {
    id: "keelung-haunted-hospital",
    position: [25.12825, 121.74474],
    title: "基隆靈異醫院",
    city: "基隆市",
    district: "信義區",
    coverPhoto: "/images/default-location.jpg",
    description: "廢棄醫院，據說夜晚會有鬼影出現，令人毛骨悚然。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("ntou-dorm", {
    id: "ntou-dorm",
    position: [25.150209, 121.778541],
    title: "海洋大學宿舍",
    city: "基隆市",
    district: "中正區",
    coverPhoto: "/images/default-location.jpg",
    description: "學生間流傳的靈異故事，晚間氣氛詭異。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),

  generateMarkerData("shimen-reservoir", {
    id: "shimen-reservoir",
    position: [24.833567, 121.216837],
    title: "石門水庫",
    city: "桃園市",
    district: "龍潭區",
    coverPhoto: "/images/default-location.jpg",
    description: "傳聞有許多水鬼故事",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("jingmei-night-market", {
    id: "jingmei-night-market",
    position: [24.988846, 121.539733],
    title: "景美夜市",
    city: "台北市",
    district: "文山區",
    coverPhoto: "/images/default-location.jpg",
    description: "據說某些攤位有靈異事件發生",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("cheng-huang-temple", {
    id: "cheng-huang-temple",
    position: [24.805619, 120.968874],
    title: "新竹城隍廟",
    city: "新竹市",
    district: "北區",
    coverPhoto: "/images/default-location.jpg",
    description: "古老廟宇，曾見靈異傳聞",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("taichung-haunted-ktv", {
    id: "taichung-haunted-ktv",
    position: [24.151635, 120.665866],
    title: "台中鬧鬼KTV",
    city: "台中市",
    district: "北區",
    coverPhoto: "/images/default-location.jpg",
    description: "據說這間KTV內曾發生靈異事件，成為熱門探險地點。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("pingxi-river-ghost", {
    id: "pingxi-river-ghost",
    position: [25.032989, 121.736982],
    title: "平溪河邊幽靈",
    city: "新北市",
    district: "平溪區",
    coverPhoto: "/images/default-location.jpg",
    description: "傳聞河邊夜晚經常出現神秘的白影，令人不寒而慄。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
  generateMarkerData("alishan-ghost-trail", {
    id: "alishan-ghost-trail",
    position: [23.508038, 120.806392],
    title: "阿里山靈異步道",
    city: "嘉義縣",
    district: "阿里山鄉",
    coverPhoto: "/images/default-location.jpg",
    description: "阿里山著名步道之一，據說深夜時分常聽到神秘腳步聲。",
    userId: "system",
    userName: "系統管理員",
    userAvatar: "/images/Avatars/avatar (1).jpg",
  }),
    generateMarkerData("taoyuan-haunted-university", {
      id: "taoyuan-haunted-university",
      position: [24.969037, 121.191308],
      title: "桃園鬧鬼大學",
      city: "桃園市",
      district: "大溪區",
      coverPhoto: "/images/default-location.jpg",
      description: "這所廢棄的校舍被認為是靈異探險愛好者的天堂。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("yushan-ghost-spot", {
      id: "yushan-ghost-spot",
      position: [23.471234, 120.957865],
      title: "玉山靈異地點",
      city: "南投縣",
      district: "信義鄉",
      coverPhoto: "/images/default-location.jpg",
      description: "據說登山客在夜晚經常聽到莫名的聲響和腳步聲。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("kaohsiung-haunted-ktv", {
      id: "kaohsiung-haunted-ktv",
      position: [22.627278, 120.301435],
      title: "高雄鬧鬼KTV",
      city: "高雄市",
      district: "前金區",
      coverPhoto: "/images/default-location.jpg",
      description: "這間廢棄KTV據說有許多靈異故事流傳。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("nantou-river-ghost", {
      id: "nantou-river-ghost",
      position: [23.919619, 120.862404],
      title: "南投溪邊幽靈",
      city: "南投縣",
      district: "魚池鄉",
      coverPhoto: "/images/default-location.jpg",
      description: "當地居民傳說溪邊經常出現白影和怪聲。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("tainan-haunted-mansion", {
      id: "tainan-haunted-mansion",
      position: [22.987753, 120.218231],
      title: "台南鬧鬼古宅",
      city: "台南市",
      district: "中西區",
      coverPhoto: "/images/default-location.jpg",
      description: "這座歷史悠久的古宅流傳許多靈異傳說。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("hualien-haunted-monument", {
      id: "hualien-haunted-monument",
      position: [23.987567, 121.604413],
      title: "花蓮鬧鬼古蹟",
      city: "花蓮縣",
      district: "花蓮市",
      coverPhoto: "/images/default-location.jpg",
      description: "這座古蹟因其陰森的氛圍而聞名。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("kenting-abandoned-villa", {
      id: "kenting-abandoned-villa",
      position: [21.947776, 120.780472],
      title: "墾丁廢棄別墅",
      city: "屏東縣",
      district: "恆春鎮",
      coverPhoto: "/images/default-location.jpg",
      description: "這棟廢棄別墅多年來無人敢靠近，傳聞四起。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("chiayi-abandoned-hotel", {
      id: "chiayi-abandoned-hotel",
      position: [23.465308, 120.445844],
      title: "嘉義廢棄旅館",
      city: "嘉義縣",
      district: "番路鄉",
      coverPhoto: "/images/default-location.jpg",
      description: "這間旅館已被廢棄多年，內部充滿陰森的氣息。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
    generateMarkerData("taitung-haunted-bridge", {
      id: "taitung-haunted-bridge",
      position: [22.755311, 121.139956],
      title: "台東鬧鬼橋樑",
      city: "台東縣",
      district: "台東市",
      coverPhoto: "/images/default-location.jpg",
      description: "這座橋樑據說是當地最靈異的地方之一。",
      userId: "system",
      userName: "系統管理員",
      userAvatar: "/images/Avatars/avatar (1).jpg",
    }),
];


export default defaultMarkers;